apiVersion: v1
kind: PersistentVolume
metadata:
  name: traefik-certs-pv
spec:
  capacity:
    storage: 128Mi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  storageClassName: local-storage
  local:
    path: /mnt/kube-volumes/traefik-certs  # CORRECT PATH: /mnt/kube-volumes/traefik-certs
  nodeAffinity:  # <-- RE-INTRODUCING nodeAffinity - IT IS REQUIRED
    required:
      nodeSelectorTerms:
        - matchExpressions:
            - key: kubernetes.io/hostname
              operator: In
              values:
                - daemon  # <-- Ensure 'daemon' is the correct node name from 'kubectl get nodes' output
