apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: traefik
  namespace: argocd
spec:
  project: default
  source:
    repoURL: "git@github.com:wrightpt/elk-stack-kubernetes-simplified.git"  # Your repo URL
    targetRevision: "main"
    path: helm/traefik
  destination:
    server: "https://kubernetes.default.svc"
    namespace: "traefik"
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
