apiVersion: v1
kind: PersistentVolume
metadata:
  name: traefik-certs-pv
spec:
  capacity:
    storage: 128Mi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  storageClassName: local-storage
  local:
    path: /mnt/kube-volumes/traefik-certs  # <-- ENSURE THIS IS /mnt/kube-volumes/traefik-certs
  nodeAffinity:
    required:
      nodeSelectorTerms:
        - matchExpressions:
            - key: kubernetes.io/hostname
              operator: In
              values:
                - daemon
