# Define the service configuration for Traefik
service:
  type: LoadBalancer
  # Specify the external IP to match your current setup (optional, depending on your cluster)
  externalIPs:
    - 192.168.1.240
  ports:
    # HTTP port configuration
    web:
      port: 80
      protocol: TCP
      # Node port is optional; Kubernetes manages it automatically for LoadBalancer services
      # Uncomment if you need to enforce the exact node port from your current setup
      # nodePort: 31421
    # HTTPS port configuration
    websecure:
      port: 443
      protocol: TCP
      # Uncomment if you need to enforce the exact node port
      # nodePort: 30887

# Enable the Traefik dashboard for monitoring (optional but recommended)
dashboard:
  enabled: true
  # Optionally set a domain for the dashboard if you’ll access it externally via Ingress
  # Replace with your actual domain if applicable
  # domain: traefik-dashboard.yourdomain.com

# Configure an IngressRoute for the dashboard (optional)
ingressRoute:
  dashboard:
    enabled: true
    # Define the rule for accessing the dashboard
    # Replace 'traefik.yourdomain.com' with your domain or a local hostname
    rule: "Host(`traefik.local`) && PathPrefix(`/dashboard`)"

# Enable Kubernetes providers to allow Traefik to discover services and ingresses
providers:
  kubernetesCRD:
    enabled: true
  kubernetesIngress:
    enabled: true

# Optional: Add annotations if your cluster requires them for the LoadBalancer
# annotations:
#   metallb.universe.tf/address-pool: "default"  # Example for MetalLB, adjust as needed

# Optional: Configure additional Traefik settings
# logs:
#   general:
#     level: DEBUG  # Useful for troubleshooting
