kibana:
  image:
    repository: "kibana"
    tag: "7.17.3"
  
  elasticsearchHosts: "http://elasticsearch-master:9200"
  
  resources:
    requests:
      cpu: "500m"
      memory: "1Gi"
    limits:
      cpu: "1"
      memory: "2Gi"
  
  persistence:
    enabled: true
    storageClass: "local-storage"
    size: "5Gi"
  
  service:
    type: LoadBalancer
    port: 5601
  
  securityContext:
    enabled: true
    runAsUser: 1000
    fsGroup: 1000
  
  kibanaConfig:
    kibana.yml: |
      server.host: "0.0.0.0"
      server.publicBaseUrl: "https://kibana.1xmr.com"
      elasticsearch.username: "kibana_admin"
      elasticsearch.ssl.verificationMode: none
      logging:
        appenders:
          file:
            type: file
            fileName: /var/log/kibana/kibana.log
            layout:
              type: json
        root:
          appenders:
            - default
            - file
      pid.file: /run/kibana/kibana.pid
  
  # Fix the extraEnvs format:
  extraEnvs:
    - name: ELASTICSEARCH_USERNAME
      valueFrom:
        secretKeyRef:
          name: kibana-credentials
          key: username
    - name: ELASTICSEARCH_PASSWORD
      valueFrom:
        secretKeyRef:
          name: kibana-credentials
          key: password
